version: '3.4'

services:
  mongo:
    image: mongo
    container_name: ecommerce_mongodb
    restart: always
    ports:
      - "27017:27017"

  ecommerce.backend.api:
    container_name: ecommerce_backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001;http://+:5000
      MongoDB__Host: mongo
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: always
    depends_on:
      - mongo